FROM node:latest
# RUN mkdir -p /app/public /app/src
WORKDIR /app

# COPY package.json /app/package.json
# COPY package-lock.json /app/package-lock.json
COPY . /app
# COPY index.html /app/index.html
# COPY src /app/src
# COPY public /app/public

RUN npm install

EXPOSE 5173
# CMD ["npm", "list", "vite"]
CMD ["npm", "run", "dev"]
